// <auto-generated />
using System;
using Intap.FirstProject.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intap.FirstProject.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intap.FirstProject.Domain.Categorias.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Categorias_Estado");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categorias_Nombre");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Empleados.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Cargo")
                        .HasDatabaseName("IX_Empleados_Cargo");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Empleados_Correo");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Empleados_Estado");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasDatabaseName("UQ_Empleados_Identificacion");

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Permissions.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Code");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "view_users",
                            Module = "Users",
                            Name = "View Users"
                        },
                        new
                        {
                            Code = "create_users",
                            Module = "Users",
                            Name = "Create Users"
                        },
                        new
                        {
                            Code = "edit_users",
                            Module = "Users",
                            Name = "Edit Users"
                        },
                        new
                        {
                            Code = "delete_users",
                            Module = "Users",
                            Name = "Delete Users"
                        },
                        new
                        {
                            Code = "view_projects",
                            Module = "Projects",
                            Name = "View Projects"
                        },
                        new
                        {
                            Code = "create_projects",
                            Module = "Projects",
                            Name = "Create Projects"
                        },
                        new
                        {
                            Code = "edit_projects",
                            Module = "Projects",
                            Name = "Edit Projects"
                        },
                        new
                        {
                            Code = "delete_projects",
                            Module = "Projects",
                            Name = "Delete Projects"
                        },
                        new
                        {
                            Code = "view_tasks",
                            Module = "Tasks",
                            Name = "View Tasks"
                        },
                        new
                        {
                            Code = "create_tasks",
                            Module = "Tasks",
                            Name = "Create Tasks"
                        },
                        new
                        {
                            Code = "edit_tasks",
                            Module = "Tasks",
                            Name = "Edit Tasks"
                        },
                        new
                        {
                            Code = "delete_tasks",
                            Module = "Tasks",
                            Name = "Delete Tasks"
                        },
                        new
                        {
                            Code = "view_roles",
                            Module = "Roles",
                            Name = "View Roles"
                        },
                        new
                        {
                            Code = "create_roles",
                            Module = "Roles",
                            Name = "Create Roles"
                        },
                        new
                        {
                            Code = "edit_roles",
                            Module = "Roles",
                            Name = "Edit Roles"
                        },
                        new
                        {
                            Code = "delete_roles",
                            Module = "Roles",
                            Name = "Delete Roles"
                        });
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("IX_Projects_CategoriaId");

                    b.HasIndex("Name");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Projects.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("ProjectMembers", (string)null);
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standard user access",
                            IsActive = true,
                            IsSystem = true,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Roles.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("character varying(100)");

                    b.HasKey("RoleId", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "view_users"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "create_users"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "edit_users"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "delete_users"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "view_projects"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "create_projects"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "edit_projects"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "delete_projects"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "view_tasks"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "create_tasks"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "edit_tasks"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "delete_tasks"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "view_roles"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "create_roles"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "edit_roles"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionCode = "delete_roles"
                        });
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.SubCategorias.SubCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("IX_SubCategorias_CategoriaId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_SubCategorias_Estado");

                    b.HasIndex("Nombre", "CategoriaId")
                        .IsUnique()
                        .HasDatabaseName("UQ_SubCategorias_Nombre_CategoriaId_Activas")
                        .HasFilter("\"Estado\" = true");

                    b.ToTable("SubCategorias", (string)null);
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Tasks.TaskEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "Date");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.TiposProyectos.TipoProyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_TiposProyecto_Estado");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_TiposProyecto_Nombre_Activos")
                        .HasFilter("\"Estado\" = TRUE");

                    b.ToTable("TiposProyecto", (string)null);
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.TiposTareas.TipoTarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_TiposTarea_Estado");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_TiposTarea_Nombre_Activos")
                        .HasFilter("\"Estado\" = TRUE");

                    b.ToTable("TiposTarea", (string)null);
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Identification")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<string>("Position")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Projects.Project", b =>
                {
                    b.HasOne("Intap.FirstProject.Domain.Categorias.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Projects.ProjectMember", b =>
                {
                    b.HasOne("Intap.FirstProject.Domain.Projects.Project", null)
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intap.FirstProject.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Roles.RolePermission", b =>
                {
                    b.HasOne("Intap.FirstProject.Domain.Permissions.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Intap.FirstProject.Domain.Roles.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.SubCategorias.SubCategoria", b =>
                {
                    b.HasOne("Intap.FirstProject.Domain.Categorias.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SubCategorias_Categorias");
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Tasks.TaskEntry", b =>
                {
                    b.HasOne("Intap.FirstProject.Domain.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Intap.FirstProject.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Users.User", b =>
                {
                    b.HasOne("Intap.FirstProject.Domain.Roles.Role", "AssignedRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedRole");
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Projects.Project", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Intap.FirstProject.Domain.Roles.Role", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
